### ISSUE TITLE
Insightful Connection to MATHVERSE

### ISSUE THREAD

**Issue by Zhenwen-NLP** [ZrrSkywalker/MathVerse#1]
Hi, I read the MathVerse paper and it is great work, congratulations! I believe that it could provide valuable insights into the reasoning abilities of MLLM. 

I am wondering if you might consider citing our work [https://scemqa.github.io/] in your paper, as it could provide additional depth to the understanding and implications of similar for the readers. It could be beneficial for the MLLM community to see the connection between our works.

Please understand that my intention is only to suggest a potential enhancement to your already excellent paper. I would be more than happy to discuss this further or provide any additional information you might need regarding my work.

Zhenwen

**Comment by ZrrSkywalker** [comment]
Hi Zhenwen, thanks for your interest in MathVerse. SceMQA is also a comprehensive benchmark for multi-modal scientific problems including mathematics at the college entrance level, which I believe could demonstrate unique views for MLLM development. We will include your work and discuss our differences in the next version. Thanks!

Renrui

**Comment by Zhenwen-NLP** [comment]
Thanks!
