### ISSUE TITLE
Method for multi-step scoring (CoT evaluation strategy) ?

### ISSUE THREAD

**Issue by mozzie-pluto** [ZrrSkywalker/MathVerse#3]
Hi, I was reading through your code and paper to understand how CoT evaluation strategy works. I wanted to understand exactly how the scoring of the reasoning steps is done, specifically what are the prompts used for multi-step marking?

My understand of the CoT evaluation strategy from the paper is
1. Given any MLLM model output, use GPT-4 to split into list of steps. (This prompt is not in the prompts.py, as far as i understand, but should be simple enough)
2. Given the list of steps of MLLM reasoning, and the original question, diagram and the ground truth answer (only the choice, no explanation) - we send to GPT-4V to compute a multi-step score. But I cannot understand what prompts are used here, and also how are you ensuring the correctness of the GPT-4V scores
3. Additionally, the paper mentions "annotate additional information for function problems" - Can I know what is this additional information?

**Comment by ZrrSkywalker** [comment]
Thanks for your interest! We provide sufficient details in the Appendix of our [paper](https://arxiv.org/pdf/2403.14624.pdf).
1. Yes, for this first-step extraction, the prompt for GPT-4 is listed in Table 7, Page 22, Appendix.
2. Yes, the second-step scoring prompt for GPT-4V is also listed in Table 7, Page 22, Appendix. We also show many CoT evaluation cases from Pages 23 ~ 46.
3. The additional annotation for functions is their expression and some simple properties, as shown in Figure 11, Page 23, Appendix.

**Comment by mozzie-pluto** [comment]
Thanks!
